namespace Blaze15SDK.Blaze.GameManager;

public enum DatalessContext : int
{
    CREATE_GAME_SETUP_CONTEXT,
    JOIN_GAME_SETUP_CONTEXT,
    INDIRECT_JOIN_GAME_FROM_QUEUE_SETUP_CONTEXT,
    INDIRECT_JOIN_GAME_FROM_RESERVATION_CONTEXT,
    HOST_INJECTION_SETUP_CONTEXT,
}
