namespace Blaze15SDK.Blaze.GameManager;

public enum GameDestructionReason : int
{
    SYS_GAME_ENDING,
    SYS_CREATION_FAILED,
    SYS_GAME_RECREATE,
    SYS_GAME_FAILED_CONNECTION_VALIDATION,
    HOST_LEAVING,
    HOST_INJECTION,
    HOST_EJECTION,
    LOCAL_PLAYER_LEAVING,
    TITLE_REASON_BASE_GAME_DESTRUCTION_REASON,
}
