namespace Blaze15SDK.Blaze.GameManager;

public enum JoinMethod : int
{
    SYS_JOIN_TYPE_INVALID = 0x0,
    JOIN_BY_BROWSING = 0x1,
    JOIN_BY_MATCHMAKING = 0x2,
    JOIN_BY_INVITES = 0x4,
    JOIN_BY_PERSISTED_GAME_ID = 0x5,
    JOIN_BY_PLAYER = 0x8,
    SYS_JOIN_BY_FOLLOWLEADER_CREATEGAME = 0x0F,
    SYS_JOIN_BY_RESETDEDICATEDSERVER = 0x10,
    SYS_JOIN_BY_FOLLOWLEADER_RESETDEDICATEDSERVER = 0x20,
    SYS_JOIN_BY_FOLLOWLEADER_CREATEGAME_HOST = 0x40,
    SYS_JOIN_BY_CREATE = 0x50,
    SYS_JOIN_BY_FOLLOWLEADER_RESERVEDEXTERNALPLAYER = 0x60,
    SYS_JOIN_BY_FOLLOWLOCALUSER = 0x70,
}
