namespace Blaze15SDK.Blaze.GameManager;

public enum MatchmakingContextEnum : int
{
    MATCHMAKING_CONTEXT_MATCHMAKER_CREATE_GAME,
    MATCHMAKING_CONTEXT_MATCHMAKER_FIND_GAME,
    MATCHMAKING_CONTEXT_GAMEBROWSER,
    MATCHMAKING_CONTEXT_FIND_DEDICATED_SERVER,
}
