namespace Blaze15SDK.Blaze.GameManager;

public enum MatchmakingResult : int
{
    SUCCESS_CREATED_GAME,
    SUCCESS_JOINED_NEW_GAME,
    SUCCESS_JOINED_EXISTING_GAME,
    SESSION_TIMED_OUT,
    SESSION_CANCELED,
    SESSION_TERMINATED,
    SESSION_ERROR_GAME_SETUP_FAILED,
    SESSION_QOS_VALIDATION_FAILED,
    SUCCESS_PSEUDO_CREATE_GAME,
    SUCCESS_PSEUDO_FIND_GAME,
}
