namespace Blaze15SDK.Blaze.GameManager;

public enum UpdateExternalSessionPresenceForUserReason : int
{
    UPDATE_PRESENCE_REASON_GAME_CREATE = 0x00,
    UPDATE_PRESENCE_REASON_GAME_JOIN = 0x01,
    UPDATE_PRESENCE_REASON_GAME_LEAVE = 0x02,
    UPDATE_PRESENCE_REASON_TEAM_CHANGE = 0x03,
    UPDATE_PRESENCE_REASON_GAME_NEWROUND = 0x04,
}
