namespace Blaze15SDK.Blaze;

public enum ExternalSessionType : int {
    EXTERNAL_SESSION_INVALID = 0x0,
    EXTERNAL_SESSION_GAME = 0x01,
    EXTERNAL_SESSION_MATCHMAKING_SESSION = 0x02,
    EXTERNAL_SESSION_GAME_GROUP = 0x03,
    EXTERNAL_SESSION_MATCHMAKING_SCENARIO = 0x04,
}
