namespace Blaze15SDK.Blaze;

public enum UserSessionForcedLogoutType : int {
    FORCED_LOGOUTTYPE_INVALID = 0,
    FORCED_LOGOUTTYPE_RELOGIN_REQUIRED = 1,
    FORCED_LOGOUTTYPE_LOGGEDIN_ELSEWHERE = 2,
    FORCED_LOGOUTTYPE_ACCESS_REVOKED = 3,
}
