namespace Blaze15SDK.Blaze.Clubs;

public enum ClubLogEventKeyType : int
{
    CLUB_LOG_EVENT_CREATE_CLUB = 0,
    CLUB_LOG_EVENT_JOIN_CLUB = 1,
    CLUB_LOG_EVENT_LEAVE_CLUB = 2,
    CLUB_LOG_EVENT_REMOVED_FROM_CLUB = 3,
    CLUB_LOG_EVENT_AWARD_TROPHY = 4,
    CLUB_LOG_EVENT_GM_PROMOTED = 5,
    CLUB_LOG_EVENT_GM_DEMOTED = 6,
    CLUB_LOG_EVENT_OWNERSHIP_TRANSFERRED = 7,
    CLUB_LOG_EVENT_FORCED_CLUB_NAME_CHANGE = 8,
    CLUB_LOG_EVENT_MAX_CLUB_NAME_CHANGES = 9,
}
