namespace Blaze15SDK.Blaze.Clubs;

public enum MemberOnlineStatus : int
{
    CLUBS_MEMBER_OFFLINE = 0,
    CLUBS_MEMBER_ONLINE_INTERACTIVE = 1,
    CLUBS_MEMBER_ONLINE_NON_INTERACTIVE = 2,
    CLUBS_MEMBER_IN_GAMEROOM = 3,
    CLUBS_MEMBER_IN_OPEN_SESSION = 4,
    CLUBS_MEMBER_IN_GAME = 5,
    CLUBS_MEMBER_CUSTOM_ONLINE_STATUS = 6,
    CLUBS_MEMBER_CUSTOM_ONLINE_STATUS_1 = 6,
    CLUBS_MEMBER_CUSTOM_ONLINE_STATUS_2 = 7,
    CLUBS_MEMBER_CUSTOM_ONLINE_STATUS_3 = 8,
    CLUBS_MEMBER_CUSTOM_ONLINE_STATUS_4 = 9,
    CLUBS_MEMBER_CUSTOM_ONLINE_STATUS_5 = 10,
    CLUBS_MEMBER_CUSTOM_ONLINE_STATUS_6 = 11,
    CLUBS_MEMBER_CUSTOM_ONLINE_STATUS_7 = 12,
    CLUBS_MEMBER_CUSTOM_ONLINE_STATUS_8 = 13,
    CLUBS_MEMBER_ONLINE_STATUS_COUNT = 14,
}
