namespace Blaze15SDK.Blaze.Clubs;

public enum UpdateReason : int
{
    UPDATE_REASON_USER_SESSION_CREATED,
    UPDATE_REASON_USER_SESSION_DESTROYED,
    UPDATE_REASON_USER_JOINED_CLUB,
    UPDATE_REASON_USER_LEFT_CLUB,
    UPDATE_REASON_USER_ONLINE_STATUS_UPDATED,
    UPDATE_REASON_CLUB_DESTROYED,
    UPDATE_REASON_CLUB_CREATED,
    UPDATE_REASON_CLUB_SETTINGS_UPDATED,
    UPDATE_REASON_USER_PROMOTED_TO_GM,
    UPDATE_REASON_USER_DEMOTED_TO_MEMBER,
    UPDATE_REASON_TRANSFER_OWNERSHIP,
}
