namespace Blaze15SDK.Blaze.Stats;

public enum WipeStatsOperation : int
{
    WIPE_STATS_OPERATION_INVALID = 0,
    DELETE_BY_CATEGORY_KEYSCOPE_USERSET = 1,
    DELETE_BY_CATEGORY_KEYSCOPE_ENTITYID = 2,
    DELETE_BY_KEYSCOPE_USERSET = 3,
    DELETE_BY_KEYSCOPE_ENTITYID = 4,
    DELETE_BY_ENTITYID = 5,
    DELETE_BY_CATEGORY = 6,
    DELETE_BY_CATEGORY_ENTITYID = 7,
    DELETE_BY_CATEGORY_KEYSCOPE = 8,
}
